# coding=utf-8

dates = [
    "1980",
    "1981",
    "1982",
    "1983",
    "1984",
    "1985",
    "1986",
    "1987",
    "1988",
    "1989",
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2010",
    "2016",
    "2017",
    "2018",
    "hoy",
    "este mes",
    "este año",
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
    ]

indexes = [
    "Desempleo",
    "Poblacion",
    "Porcentaje poblacion",
    "Variacion poblacion",
    "Variacion desempleo"
    ]

locations = [
    "35000",
    "38000",
    "38201",
    "España",
    "Tenerife",
    "Canarias",
    "Las Palmas",
    "Fuerteventura",
    "Antigua",
    "Betancuria",
    "La Oliva",
    "Puerto del Rosario",
    "Pájara",
    "Tuineje",
    "Gran Canaria",
    "Arucas",
    "Las Palmas de Gran Canaria",
    "Santa Brígida",
    "Telde",
    "Firgas",
    "Teror",
    "Valsequillo de Gran Canaria",
    "Valleseco",
    "Vega de San Mateo",
    "Agaete",
    "Gáldar",
    "Moya",
    "Santa María de Guía de Gran Canaria",
    "Artenara",
    "La Aldea de San Nicolás",
    "Tejeda",
    "Mogán",
    "San Bartolomé de Tirajana",
    "Agüimes",
    "Ingenio",
    "Santa Lucía de Tirajana",
    "Lanzarote",
    "Arrecife",
    "San Bartolomé",
    "Tías",
    "Haría",
    "Teguise",
    "Tinajo",
    "Yaiza",
    "Santa Cruz de Tenerife",
    "El Hierro",
    "Frontera",
    "Valverde",
    "El Pinar de El Hierro",
    "La Gomera",
    "Agulo",
    "Hermigua",
    "Vallehermoso",
    "Alajeró",
    "San Sebastián de La Gomera",
    "Valle Gran Rey",
    "La Palma",
    "Breña Alta",
    "Breña Baja",
    "Santa Cruz de La Palma",
    "Villa de Mazo",
    "Barlovento",
    "Puntallana",
    "San Andrés y Sauces",
    "Garafía",
    "Puntagorda",
    "Tijarafe",
    "Fuencaliente de La Palma",
    "Los Llanos de Aridane",
    "El Paso",
    "Tazacorte",
    "Tenerife",
    "San Cristóbal de La Laguna",
    "El Rosario",
    "Santa Cruz de Tenerife",
    "Tegueste",
    "La Matanza de Acentejo",
    "Santa Úrsula",
    "El Sauzal",
    "Tacoronte",
    "La Victoria de Acentejo",
    "Buenavista del Norte",
    "Garachico",
    "Los Silos",
    "El Tanque",
    "La Guancha",
    "Icod de los Vinos",
    "San Juan de la Rambla",
    "La Orotava",
    "Puerto de la Cruz",
    "Los Realejos",
    "Arico",
    "Fasnia",
    "Granadilla de Abona",
    "San Miguel de Abona",
    "Vilaflor de Chasna",
    "Adeje",
    "Arona",
    "Guía de Isora",
    "Santiago del Teide",
    "Arafo",
    "Candelaria",
    "Güímar"
]
